// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: recordgetter.proto

package proto

import (
	proto "github.com/brotherlogic/recordcollection/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_DEFAULT  RequestType = 0
	RequestType_AUDITION RequestType = 1
	RequestType_DIGITAL  RequestType = 2
	RequestType_CD_FOCUS RequestType = 3
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "DEFAULT",
		1: "AUDITION",
		2: "DIGITAL",
		3: "CD_FOCUS",
	}
	RequestType_value = map[string]int32{
		"DEFAULT":  0,
		"AUDITION": 1,
		"DIGITAL":  2,
		"CD_FOCUS": 3,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_recordgetter_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_recordgetter_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_recordgetter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{0}
}

type DiskScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    int32                  `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DiskNumber    int32                  `protobuf:"varint,2,opt,name=disk_number,json=diskNumber,proto3" json:"disk_number,omitempty"`
	ScoreDate     int64                  `protobuf:"varint,3,opt,name=score_date,json=scoreDate,proto3" json:"score_date,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskScore) Reset() {
	*x = DiskScore{}
	mi := &file_recordgetter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskScore) ProtoMessage() {}

func (x *DiskScore) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskScore.ProtoReflect.Descriptor instead.
func (*DiskScore) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{1}
}

func (x *DiskScore) GetInstanceId() int32 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *DiskScore) GetDiskNumber() int32 {
	if x != nil {
		return x.DiskNumber
	}
	return 0
}

func (x *DiskScore) GetScoreDate() int64 {
	if x != nil {
		return x.ScoreDate
	}
	return 0
}

func (x *DiskScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPick   *proto.Record          `protobuf:"bytes,1,opt,name=current_pick,json=currentPick,proto3" json:"current_pick,omitempty"`
	Scores        []*DiskScore           `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	ActiveFolders []int32                `protobuf:"varint,3,rep,packed,name=active_folders,json=activeFolders,proto3" json:"active_folders,omitempty"`
	LastSeven     int64                  `protobuf:"varint,4,opt,name=last_seven,json=lastSeven,proto3" json:"last_seven,omitempty"`
	SevenCount    int32                  `protobuf:"varint,5,opt,name=seven_count,json=sevenCount,proto3" json:"seven_count,omitempty"`
	SevenDay      int32                  `protobuf:"varint,6,opt,name=seven_day,json=sevenDay,proto3" json:"seven_day,omitempty"`
	// The time we pulled a want rather than an existing record
	LastWant           int64            `protobuf:"varint,7,opt,name=last_want,json=lastWant,proto3" json:"last_want,omitempty"`
	AuditionPick       int32            `protobuf:"varint,8,opt,name=audition_pick,json=auditionPick,proto3" json:"audition_pick,omitempty"`
	CurrentDigitalPick int32            `protobuf:"varint,9,opt,name=current_digital_pick,json=currentDigitalPick,proto3" json:"current_digital_pick,omitempty"`
	CurrentCdPick      int32            `protobuf:"varint,15,opt,name=current_cd_pick,json=currentCdPick,proto3" json:"current_cd_pick,omitempty"`
	CurrDate           int32            `protobuf:"varint,10,opt,name=curr_date,json=currDate,proto3" json:"curr_date,omitempty"`
	ValidCount         int32            `protobuf:"varint,11,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`
	UnlistenedCount    int32            `protobuf:"varint,13,opt,name=unlistened_count,json=unlistenedCount,proto3" json:"unlistened_count,omitempty"`
	CatCount           map[int32]int32  `protobuf:"bytes,12,rep,name=cat_count,json=catCount,proto3" json:"cat_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ScoreCount         map[int32]int32  `protobuf:"bytes,14,rep,name=score_count,json=scoreCount,proto3" json:"score_count,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CattypeCount       map[string]int32 `protobuf:"bytes,16,rep,name=cattype_count,json=cattypeCount,proto3" json:"cattype_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Issue              int32            `protobuf:"varint,17,opt,name=issue,proto3" json:"issue,omitempty"`
	Work               int32            `protobuf:"varint,18,opt,name=work,proto3" json:"work,omitempty"`
	Sales              int32            `protobuf:"varint,19,opt,name=sales,proto3" json:"sales,omitempty"`
	TwelvePhs          int32            `protobuf:"varint,20,opt,name=twelve_phs,json=twelvePhs,proto3" json:"twelve_phs,omitempty"`
	TwlevePic          int32            `protobuf:"varint,21,opt,name=twleve_pic,json=twlevePic,proto3" json:"twleve_pic,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_recordgetter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetCurrentPick() *proto.Record {
	if x != nil {
		return x.CurrentPick
	}
	return nil
}

func (x *State) GetScores() []*DiskScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *State) GetActiveFolders() []int32 {
	if x != nil {
		return x.ActiveFolders
	}
	return nil
}

func (x *State) GetLastSeven() int64 {
	if x != nil {
		return x.LastSeven
	}
	return 0
}

func (x *State) GetSevenCount() int32 {
	if x != nil {
		return x.SevenCount
	}
	return 0
}

func (x *State) GetSevenDay() int32 {
	if x != nil {
		return x.SevenDay
	}
	return 0
}

func (x *State) GetLastWant() int64 {
	if x != nil {
		return x.LastWant
	}
	return 0
}

func (x *State) GetAuditionPick() int32 {
	if x != nil {
		return x.AuditionPick
	}
	return 0
}

func (x *State) GetCurrentDigitalPick() int32 {
	if x != nil {
		return x.CurrentDigitalPick
	}
	return 0
}

func (x *State) GetCurrentCdPick() int32 {
	if x != nil {
		return x.CurrentCdPick
	}
	return 0
}

func (x *State) GetCurrDate() int32 {
	if x != nil {
		return x.CurrDate
	}
	return 0
}

func (x *State) GetValidCount() int32 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *State) GetUnlistenedCount() int32 {
	if x != nil {
		return x.UnlistenedCount
	}
	return 0
}

func (x *State) GetCatCount() map[int32]int32 {
	if x != nil {
		return x.CatCount
	}
	return nil
}

func (x *State) GetScoreCount() map[int32]int32 {
	if x != nil {
		return x.ScoreCount
	}
	return nil
}

func (x *State) GetCattypeCount() map[string]int32 {
	if x != nil {
		return x.CattypeCount
	}
	return nil
}

func (x *State) GetIssue() int32 {
	if x != nil {
		return x.Issue
	}
	return 0
}

func (x *State) GetWork() int32 {
	if x != nil {
		return x.Work
	}
	return 0
}

func (x *State) GetSales() int32 {
	if x != nil {
		return x.Sales
	}
	return 0
}

func (x *State) GetTwelvePhs() int32 {
	if x != nil {
		return x.TwelvePhs
	}
	return 0
}

func (x *State) GetTwlevePic() int32 {
	if x != nil {
		return x.TwlevePic
	}
	return 0
}

type GetRecordRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Refresh       bool                           `protobuf:"varint,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Type          RequestType                    `protobuf:"varint,2,opt,name=type,proto3,enum=recordgetter.RequestType" json:"type,omitempty"`
	Filling       proto.ReleaseMetadata_FileSize `protobuf:"varint,3,opt,name=filling,proto3,enum=recordcollection.ReleaseMetadata_FileSize" json:"filling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_recordgetter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecordRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

func (x *GetRecordRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_DEFAULT
}

func (x *GetRecordRequest) GetFilling() proto.ReleaseMetadata_FileSize {
	if x != nil {
		return x.Filling
	}
	return proto.ReleaseMetadata_FileSize(0)
}

type GetRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *proto.Record          `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	NumListens    int32                  `protobuf:"varint,2,opt,name=num_listens,json=numListens,proto3" json:"num_listens,omitempty"`
	Disk          int32                  `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordResponse) Reset() {
	*x = GetRecordResponse{}
	mi := &file_recordgetter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResponse) ProtoMessage() {}

func (x *GetRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResponse.ProtoReflect.Descriptor instead.
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{4}
}

func (x *GetRecordResponse) GetRecord() *proto.Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetRecordResponse) GetNumListens() int32 {
	if x != nil {
		return x.NumListens
	}
	return 0
}

func (x *GetRecordResponse) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type ForceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RequestType            `protobuf:"varint,1,opt,name=type,proto3,enum=recordgetter.RequestType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceRequest) Reset() {
	*x = ForceRequest{}
	mi := &file_recordgetter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceRequest) ProtoMessage() {}

func (x *ForceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceRequest.ProtoReflect.Descriptor instead.
func (*ForceRequest) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{5}
}

func (x *ForceRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_DEFAULT
}

type ClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iid           int32                  `protobuf:"varint,1,opt,name=iid,proto3" json:"iid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearRequest) Reset() {
	*x = ClearRequest{}
	mi := &file_recordgetter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearRequest) ProtoMessage() {}

func (x *ClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearRequest.ProtoReflect.Descriptor instead.
func (*ClearRequest) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{6}
}

func (x *ClearRequest) GetIid() int32 {
	if x != nil {
		return x.Iid
	}
	return 0
}

type ClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearResponse) Reset() {
	*x = ClearResponse{}
	mi := &file_recordgetter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearResponse) ProtoMessage() {}

func (x *ClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recordgetter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearResponse.ProtoReflect.Descriptor instead.
func (*ClearResponse) Descriptor() ([]byte, []int) {
	return file_recordgetter_proto_rawDescGZIP(), []int{7}
}

var File_recordgetter_proto protoreflect.FileDescriptor

const file_recordgetter_proto_rawDesc = "" +
	"\n" +
	"\x12recordgetter.proto\x12\frecordgetter\x1aEgithub.com/brotherlogic/recordcollection/proto/recordcollection.proto\"\a\n" +
	"\x05Empty\"\x82\x01\n" +
	"\tDiskScore\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\x05R\n" +
	"instanceId\x12\x1f\n" +
	"\vdisk_number\x18\x02 \x01(\x05R\n" +
	"diskNumber\x12\x1d\n" +
	"\n" +
	"score_date\x18\x03 \x01(\x03R\tscoreDate\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"\x8b\b\n" +
	"\x05State\x12;\n" +
	"\fcurrent_pick\x18\x01 \x01(\v2\x18.recordcollection.RecordR\vcurrentPick\x12/\n" +
	"\x06scores\x18\x02 \x03(\v2\x17.recordgetter.DiskScoreR\x06scores\x12%\n" +
	"\x0eactive_folders\x18\x03 \x03(\x05R\ractiveFolders\x12\x1d\n" +
	"\n" +
	"last_seven\x18\x04 \x01(\x03R\tlastSeven\x12\x1f\n" +
	"\vseven_count\x18\x05 \x01(\x05R\n" +
	"sevenCount\x12\x1b\n" +
	"\tseven_day\x18\x06 \x01(\x05R\bsevenDay\x12\x1b\n" +
	"\tlast_want\x18\a \x01(\x03R\blastWant\x12#\n" +
	"\raudition_pick\x18\b \x01(\x05R\fauditionPick\x120\n" +
	"\x14current_digital_pick\x18\t \x01(\x05R\x12currentDigitalPick\x12&\n" +
	"\x0fcurrent_cd_pick\x18\x0f \x01(\x05R\rcurrentCdPick\x12\x1b\n" +
	"\tcurr_date\x18\n" +
	" \x01(\x05R\bcurrDate\x12\x1f\n" +
	"\vvalid_count\x18\v \x01(\x05R\n" +
	"validCount\x12)\n" +
	"\x10unlistened_count\x18\r \x01(\x05R\x0funlistenedCount\x12>\n" +
	"\tcat_count\x18\f \x03(\v2!.recordgetter.State.CatCountEntryR\bcatCount\x12D\n" +
	"\vscore_count\x18\x0e \x03(\v2#.recordgetter.State.ScoreCountEntryR\n" +
	"scoreCount\x12J\n" +
	"\rcattype_count\x18\x10 \x03(\v2%.recordgetter.State.CattypeCountEntryR\fcattypeCount\x12\x14\n" +
	"\x05issue\x18\x11 \x01(\x05R\x05issue\x12\x12\n" +
	"\x04work\x18\x12 \x01(\x05R\x04work\x12\x14\n" +
	"\x05sales\x18\x13 \x01(\x05R\x05sales\x12\x1d\n" +
	"\n" +
	"twelve_phs\x18\x14 \x01(\x05R\ttwelvePhs\x12\x1d\n" +
	"\n" +
	"twleve_pic\x18\x15 \x01(\x05R\ttwlevePic\x1a;\n" +
	"\rCatCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a=\n" +
	"\x0fScoreCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11CattypeCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xa1\x01\n" +
	"\x10GetRecordRequest\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\bR\arefresh\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.recordgetter.RequestTypeR\x04type\x12D\n" +
	"\afilling\x18\x03 \x01(\x0e2*.recordcollection.ReleaseMetadata.FileSizeR\afilling\"z\n" +
	"\x11GetRecordResponse\x120\n" +
	"\x06record\x18\x01 \x01(\v2\x18.recordcollection.RecordR\x06record\x12\x1f\n" +
	"\vnum_listens\x18\x02 \x01(\x05R\n" +
	"numListens\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\x05R\x04disk\"=\n" +
	"\fForceRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.recordgetter.RequestTypeR\x04type\" \n" +
	"\fClearRequest\x12\x10\n" +
	"\x03iid\x18\x01 \x01(\x05R\x03iid\"\x0f\n" +
	"\rClearResponse*C\n" +
	"\vRequestType\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\f\n" +
	"\bAUDITION\x10\x01\x12\v\n" +
	"\aDIGITAL\x10\x02\x12\f\n" +
	"\bCD_FOCUS\x10\x032\x93\x02\n" +
	"\fRecordGetter\x12L\n" +
	"\tGetRecord\x12\x1e.recordgetter.GetRecordRequest\x1a\x1f.recordgetter.GetRecordResponse\x129\n" +
	"\bListened\x12\x18.recordcollection.Record\x1a\x13.recordgetter.Empty\x128\n" +
	"\x05Force\x12\x1a.recordgetter.ForceRequest\x1a\x13.recordgetter.Empty\x12@\n" +
	"\x05Clear\x12\x1a.recordgetter.ClearRequest\x1a\x1b.recordgetter.ClearResponseB,Z*github.com/brotherlogic/recordgetter/protob\x06proto3"

var (
	file_recordgetter_proto_rawDescOnce sync.Once
	file_recordgetter_proto_rawDescData []byte
)

func file_recordgetter_proto_rawDescGZIP() []byte {
	file_recordgetter_proto_rawDescOnce.Do(func() {
		file_recordgetter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recordgetter_proto_rawDesc), len(file_recordgetter_proto_rawDesc)))
	})
	return file_recordgetter_proto_rawDescData
}

var file_recordgetter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_recordgetter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_recordgetter_proto_goTypes = []any{
	(RequestType)(0),                    // 0: recordgetter.RequestType
	(*Empty)(nil),                       // 1: recordgetter.Empty
	(*DiskScore)(nil),                   // 2: recordgetter.DiskScore
	(*State)(nil),                       // 3: recordgetter.State
	(*GetRecordRequest)(nil),            // 4: recordgetter.GetRecordRequest
	(*GetRecordResponse)(nil),           // 5: recordgetter.GetRecordResponse
	(*ForceRequest)(nil),                // 6: recordgetter.ForceRequest
	(*ClearRequest)(nil),                // 7: recordgetter.ClearRequest
	(*ClearResponse)(nil),               // 8: recordgetter.ClearResponse
	nil,                                 // 9: recordgetter.State.CatCountEntry
	nil,                                 // 10: recordgetter.State.ScoreCountEntry
	nil,                                 // 11: recordgetter.State.CattypeCountEntry
	(*proto.Record)(nil),                // 12: recordcollection.Record
	(proto.ReleaseMetadata_FileSize)(0), // 13: recordcollection.ReleaseMetadata.FileSize
}
var file_recordgetter_proto_depIdxs = []int32{
	12, // 0: recordgetter.State.current_pick:type_name -> recordcollection.Record
	2,  // 1: recordgetter.State.scores:type_name -> recordgetter.DiskScore
	9,  // 2: recordgetter.State.cat_count:type_name -> recordgetter.State.CatCountEntry
	10, // 3: recordgetter.State.score_count:type_name -> recordgetter.State.ScoreCountEntry
	11, // 4: recordgetter.State.cattype_count:type_name -> recordgetter.State.CattypeCountEntry
	0,  // 5: recordgetter.GetRecordRequest.type:type_name -> recordgetter.RequestType
	13, // 6: recordgetter.GetRecordRequest.filling:type_name -> recordcollection.ReleaseMetadata.FileSize
	12, // 7: recordgetter.GetRecordResponse.record:type_name -> recordcollection.Record
	0,  // 8: recordgetter.ForceRequest.type:type_name -> recordgetter.RequestType
	4,  // 9: recordgetter.RecordGetter.GetRecord:input_type -> recordgetter.GetRecordRequest
	12, // 10: recordgetter.RecordGetter.Listened:input_type -> recordcollection.Record
	6,  // 11: recordgetter.RecordGetter.Force:input_type -> recordgetter.ForceRequest
	7,  // 12: recordgetter.RecordGetter.Clear:input_type -> recordgetter.ClearRequest
	5,  // 13: recordgetter.RecordGetter.GetRecord:output_type -> recordgetter.GetRecordResponse
	1,  // 14: recordgetter.RecordGetter.Listened:output_type -> recordgetter.Empty
	1,  // 15: recordgetter.RecordGetter.Force:output_type -> recordgetter.Empty
	8,  // 16: recordgetter.RecordGetter.Clear:output_type -> recordgetter.ClearResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_recordgetter_proto_init() }
func file_recordgetter_proto_init() {
	if File_recordgetter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recordgetter_proto_rawDesc), len(file_recordgetter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recordgetter_proto_goTypes,
		DependencyIndexes: file_recordgetter_proto_depIdxs,
		EnumInfos:         file_recordgetter_proto_enumTypes,
		MessageInfos:      file_recordgetter_proto_msgTypes,
	}.Build()
	File_recordgetter_proto = out.File
	file_recordgetter_proto_goTypes = nil
	file_recordgetter_proto_depIdxs = nil
}
