// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordgetter.proto

package recordgetter

import (
	fmt "fmt"
	proto1 "github.com/brotherlogic/recordcollection/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5501bf15004b71, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type DiskScore struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DiskNumber           int32    `protobuf:"varint,2,opt,name=disk_number,json=diskNumber,proto3" json:"disk_number,omitempty"`
	ScoreDate            int64    `protobuf:"varint,3,opt,name=score_date,json=scoreDate,proto3" json:"score_date,omitempty"`
	Score                int32    `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskScore) Reset()         { *m = DiskScore{} }
func (m *DiskScore) String() string { return proto.CompactTextString(m) }
func (*DiskScore) ProtoMessage()    {}
func (*DiskScore) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5501bf15004b71, []int{1}
}

func (m *DiskScore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskScore.Unmarshal(m, b)
}
func (m *DiskScore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskScore.Marshal(b, m, deterministic)
}
func (m *DiskScore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskScore.Merge(m, src)
}
func (m *DiskScore) XXX_Size() int {
	return xxx_messageInfo_DiskScore.Size(m)
}
func (m *DiskScore) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskScore.DiscardUnknown(m)
}

var xxx_messageInfo_DiskScore proto.InternalMessageInfo

func (m *DiskScore) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *DiskScore) GetDiskNumber() int32 {
	if m != nil {
		return m.DiskNumber
	}
	return 0
}

func (m *DiskScore) GetScoreDate() int64 {
	if m != nil {
		return m.ScoreDate
	}
	return 0
}

func (m *DiskScore) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

type State struct {
	CurrentPick          *proto1.Record `protobuf:"bytes,1,opt,name=current_pick,json=currentPick,proto3" json:"current_pick,omitempty"`
	Scores               []*DiskScore   `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty"`
	ActiveFolders        []int32        `protobuf:"varint,3,rep,packed,name=active_folders,json=activeFolders,proto3" json:"active_folders,omitempty"`
	LastSeven            int64          `protobuf:"varint,4,opt,name=last_seven,json=lastSeven,proto3" json:"last_seven,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5501bf15004b71, []int{2}
}

func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetCurrentPick() *proto1.Record {
	if m != nil {
		return m.CurrentPick
	}
	return nil
}

func (m *State) GetScores() []*DiskScore {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *State) GetActiveFolders() []int32 {
	if m != nil {
		return m.ActiveFolders
	}
	return nil
}

func (m *State) GetLastSeven() int64 {
	if m != nil {
		return m.LastSeven
	}
	return 0
}

type GetRecordRequest struct {
	Refresh              bool     `protobuf:"varint,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordRequest) Reset()         { *m = GetRecordRequest{} }
func (m *GetRecordRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordRequest) ProtoMessage()    {}
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5501bf15004b71, []int{3}
}

func (m *GetRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordRequest.Unmarshal(m, b)
}
func (m *GetRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordRequest.Merge(m, src)
}
func (m *GetRecordRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordRequest.Size(m)
}
func (m *GetRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordRequest proto.InternalMessageInfo

func (m *GetRecordRequest) GetRefresh() bool {
	if m != nil {
		return m.Refresh
	}
	return false
}

type GetRecordResponse struct {
	Record               *proto1.Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	NumListens           int32          `protobuf:"varint,2,opt,name=num_listens,json=numListens,proto3" json:"num_listens,omitempty"`
	Disk                 int32          `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetRecordResponse) Reset()         { *m = GetRecordResponse{} }
func (m *GetRecordResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordResponse) ProtoMessage()    {}
func (*GetRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5501bf15004b71, []int{4}
}

func (m *GetRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordResponse.Unmarshal(m, b)
}
func (m *GetRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordResponse.Merge(m, src)
}
func (m *GetRecordResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordResponse.Size(m)
}
func (m *GetRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordResponse proto.InternalMessageInfo

func (m *GetRecordResponse) GetRecord() *proto1.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func (m *GetRecordResponse) GetNumListens() int32 {
	if m != nil {
		return m.NumListens
	}
	return 0
}

func (m *GetRecordResponse) GetDisk() int32 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "recordgetter.Empty")
	proto.RegisterType((*DiskScore)(nil), "recordgetter.DiskScore")
	proto.RegisterType((*State)(nil), "recordgetter.State")
	proto.RegisterType((*GetRecordRequest)(nil), "recordgetter.GetRecordRequest")
	proto.RegisterType((*GetRecordResponse)(nil), "recordgetter.GetRecordResponse")
}

func init() { proto.RegisterFile("recordgetter.proto", fileDescriptor_af5501bf15004b71) }

var fileDescriptor_af5501bf15004b71 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x8a, 0x13, 0x41,
	0x10, 0xc6, 0x99, 0x9d, 0x9d, 0xec, 0xa6, 0x12, 0x45, 0x5b, 0xc1, 0x26, 0xa0, 0x1b, 0x06, 0x84,
	0x1c, 0x24, 0xd1, 0x78, 0x12, 0xaf, 0xfb, 0x07, 0x61, 0x11, 0xe9, 0x3c, 0xc0, 0x30, 0xe9, 0xa9,
	0x4d, 0x9a, 0xcc, 0x74, 0xc7, 0xee, 0x9a, 0x05, 0x3d, 0xfa, 0x5a, 0xbe, 0x81, 0x4f, 0x25, 0xdd,
	0x3d, 0x59, 0x36, 0xee, 0x06, 0x6f, 0x53, 0xbf, 0xfa, 0xaa, 0xa6, 0xbe, 0xaa, 0x06, 0x66, 0x51,
	0x1a, 0x5b, 0xad, 0x90, 0x08, 0xed, 0x74, 0x6b, 0x0d, 0x19, 0x36, 0xbc, 0xcf, 0x46, 0x17, 0x2b,
	0x45, 0xeb, 0x76, 0x39, 0x95, 0xa6, 0x99, 0x2d, 0xad, 0xa1, 0x35, 0xda, 0xda, 0xac, 0x94, 0x9c,
	0x45, 0x95, 0x34, 0x75, 0x8d, 0x92, 0x94, 0xd1, 0xb3, 0x50, 0xfd, 0x00, 0xc7, 0xa6, 0xf9, 0x09,
	0x64, 0x17, 0xcd, 0x96, 0x7e, 0xe4, 0xbf, 0x12, 0xe8, 0x9f, 0x2b, 0xb7, 0x59, 0x48, 0x63, 0x91,
	0x9d, 0xc1, 0x40, 0x69, 0x47, 0xa5, 0x96, 0x58, 0xa8, 0x8a, 0x27, 0xe3, 0x64, 0x92, 0x09, 0xd8,
	0xa1, 0x2f, 0x95, 0x17, 0x54, 0xca, 0x6d, 0x0a, 0xdd, 0x36, 0x4b, 0xb4, 0xfc, 0x28, 0x0a, 0x3c,
	0xfa, 0x1a, 0x08, 0x7b, 0x0d, 0xe0, 0x7c, 0xab, 0xa2, 0x2a, 0x09, 0x79, 0x3a, 0x4e, 0x26, 0xa9,
	0xe8, 0x07, 0x72, 0x5e, 0x12, 0xb2, 0x97, 0x90, 0x85, 0x80, 0x1f, 0x87, 0xca, 0x18, 0xe4, 0xbf,
	0x13, 0xc8, 0x16, 0xe4, 0xf3, 0x9f, 0x61, 0x28, 0x5b, 0x6b, 0x51, 0x53, 0xb1, 0x55, 0x72, 0x13,
	0x26, 0x18, 0xcc, 0xf9, 0xf4, 0x81, 0x0d, 0x11, 0x80, 0x18, 0x74, 0xea, 0x6f, 0x4a, 0x6e, 0xd8,
	0x0c, 0x7a, 0xa1, 0x9f, 0xe3, 0x47, 0xe3, 0x74, 0x32, 0x98, 0xbf, 0x9a, 0xee, 0xad, 0xf3, 0xce,
	0xa6, 0xe8, 0x64, 0xec, 0x2d, 0x3c, 0x2d, 0x25, 0xa9, 0x5b, 0x2c, 0x6e, 0x4c, 0x5d, 0xa1, 0x75,
	0x3c, 0x1d, 0xa7, 0x93, 0x4c, 0x3c, 0x89, 0xf4, 0x32, 0x42, 0xef, 0xa9, 0x2e, 0x1d, 0x15, 0x0e,
	0x6f, 0x51, 0x87, 0xc9, 0x53, 0xd1, 0xf7, 0x64, 0xe1, 0x41, 0xfe, 0x0e, 0x9e, 0x5d, 0x21, 0x75,
	0x03, 0xe1, 0xf7, 0x16, 0x1d, 0x31, 0x0e, 0x27, 0x16, 0x6f, 0x2c, 0xba, 0x75, 0xb0, 0x70, 0x2a,
	0x76, 0x61, 0xfe, 0x13, 0x9e, 0xdf, 0x53, 0xbb, 0xad, 0xd1, 0x0e, 0xd9, 0x7b, 0xe8, 0xc5, 0x51,
	0xff, 0x6b, 0xb8, 0xd3, 0xf9, 0x43, 0xe8, 0xb6, 0x29, 0x6a, 0xe5, 0x08, 0xb5, 0xdb, 0x1d, 0x42,
	0xb7, 0xcd, 0x75, 0x24, 0x8c, 0xc1, 0xb1, 0x3f, 0x4b, 0x38, 0x41, 0x26, 0xc2, 0xf7, 0xfc, 0x4f,
	0x02, 0xc3, 0xd8, 0xe7, 0x2a, 0xac, 0x84, 0x5d, 0x43, 0xff, 0x6e, 0x18, 0xf6, 0x66, 0x7f, 0x5d,
	0xff, 0x7a, 0x1a, 0x9d, 0x1d, 0xcc, 0x77, 0x2e, 0x3e, 0xc1, 0x69, 0xfc, 0x3b, 0x56, 0xec, 0xa0,
	0x83, 0xd1, 0x8b, 0xfd, 0x36, 0xe1, 0x19, 0xb2, 0x0f, 0x90, 0x5d, 0x1a, 0x2b, 0x91, 0x3d, 0x96,
	0x7d, 0xb4, 0x64, 0xd9, 0x0b, 0x2f, 0xf9, 0xe3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x6c,
	0xd2, 0x75, 0x34, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordGetterClient is the client API for RecordGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordGetterClient interface {
	GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error)
	Listened(ctx context.Context, in *proto1.Record, opts ...grpc.CallOption) (*Empty, error)
	Force(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type recordGetterClient struct {
	cc *grpc.ClientConn
}

func NewRecordGetterClient(cc *grpc.ClientConn) RecordGetterClient {
	return &recordGetterClient{cc}
}

func (c *recordGetterClient) GetRecord(ctx context.Context, in *GetRecordRequest, opts ...grpc.CallOption) (*GetRecordResponse, error) {
	out := new(GetRecordResponse)
	err := c.cc.Invoke(ctx, "/recordgetter.RecordGetter/GetRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordGetterClient) Listened(ctx context.Context, in *proto1.Record, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/recordgetter.RecordGetter/Listened", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordGetterClient) Force(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/recordgetter.RecordGetter/Force", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordGetterServer is the server API for RecordGetter service.
type RecordGetterServer interface {
	GetRecord(context.Context, *GetRecordRequest) (*GetRecordResponse, error)
	Listened(context.Context, *proto1.Record) (*Empty, error)
	Force(context.Context, *Empty) (*Empty, error)
}

func RegisterRecordGetterServer(s *grpc.Server, srv RecordGetterServer) {
	s.RegisterService(&_RecordGetter_serviceDesc, srv)
}

func _RecordGetter_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/GetRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).GetRecord(ctx, req.(*GetRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordGetter_Listened_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.Record)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).Listened(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/Listened",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).Listened(ctx, req.(*proto1.Record))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordGetter_Force_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordGetterServer).Force(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordgetter.RecordGetter/Force",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordGetterServer).Force(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordGetter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordgetter.RecordGetter",
	HandlerType: (*RecordGetterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecord",
			Handler:    _RecordGetter_GetRecord_Handler,
		},
		{
			MethodName: "Listened",
			Handler:    _RecordGetter_Listened_Handler,
		},
		{
			MethodName: "Force",
			Handler:    _RecordGetter_Force_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordgetter.proto",
}
